### ISSUE TITLE
Failed to install 

### ISSUE THREAD

**Issue by zzxwill** [oneops/oneops.github.io-old#43]
I failed to install jekyll by 'gem install jekyll'. Did I miss any prerequisites? Thanks.

[root@a-node3 ~]# gem install jekyll
Fetching: liquid-3.0.6.gem (100%)
Successfully installed liquid-3.0.6
Fetching: kramdown-1.12.0.gem (100%)
Successfully installed kramdown-1.12.0
Fetching: mercenary-0.3.6.gem (100%)
Successfully installed mercenary-0.3.6
Fetching: safe_yaml-1.0.4.gem (100%)
Successfully installed safe_yaml-1.0.4
Fetching: colorator-1.1.0.gem (100%)
Successfully installed colorator-1.1.0
Fetching: rouge-1.11.1.gem (100%)
Successfully installed rouge-1.11.1
Fetching: sass-3.4.22.gem (100%)
Successfully installed sass-3.4.22
Fetching: jekyll-sass-converter-1.4.0.gem (100%)
Successfully installed jekyll-sass-converter-1.4.0
Fetching: rb-fsevent-0.9.7.gem (100%)
Successfully installed rb-fsevent-0.9.7
Fetching: ffi-1.9.14.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

```
/usr/bin/ruby extconf.rb
```

mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

Gem files will remain installed in /usr/local/share/gems/gems/ffi-1.9.14 for inspection.
Results logged to /usr/local/share/gems/gems/ffi-1.9.14/ext/ffi_c/gem_make.out

**Comment by mosabua** [comment]
This is the repository for the documentation. Please contact the oneops team on slack for help. oneops.slack.com
