### ISSUE TITLE
search is broken on oneops.github.io - mixed content warning

### ISSUE THREAD

**Issue by adamenger** [oneops/oneops.github.io-old#6]
Hello,

Trying to search your documentation on https://oneops.github.io/developer/ but my browser is refusing due to mixed content:

![https://i.imgur.com/an0UbaG.png](https://i.imgur.com/an0UbaG.png)

```
Mixed Content: The page at 'https://oneops.github.io/developer/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint
```

**Comment by gauravlall** [comment]
We are working on getting this fixed .

**Comment by mosabua** [comment]
Closing this issue as it is old. Please file any new issues at https://github.com/oneops/oneops.github.io/issues

cc @aliloney
